export interface Command {
  cmd: string;
  desc: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  commands: Command[];
}

export const categories: Category[] = [
  {
    id: "files",
    name: "File Operations",
    icon: "📁",
    color: "#eab308",
    commands: [
      { cmd: "ls, ll, la, l, lt", desc: "List files with details" },
      { cmd: "cd <dir>", desc: "Change directory" },
      { cmd: "cat, head, tail, less", desc: "View file contents" },
      { cmd: "pwd", desc: "Print working directory" },
      { cmd: "mkdir <dir>", desc: "Create directory" },
      { cmd: "rm <file|dir>", desc: "Remove files/directories" },
      { cmd: "touch <file>", desc: "Create empty file" },
      { cmd: "cp, mv", desc: "Copy/Move files" },
      { cmd: "ln", desc: "Create symlinks" },
      { cmd: "tree [dir]", desc: "Directory tree view" },
      { cmd: "grep, rg, find, which", desc: "Search tools" },
    ],
  },
  {
    id: "git",
    name: "Git & Version Control",
    icon: "🔴",
    color: "#f97316",
    commands: [
      { cmd: "git <cmd>", desc: "Run any git command" },
      { cmd: "status, branches, log", desc: "Git status/info" },
      { cmd: "diff, staged", desc: "View changes" },
      { cmd: "commit <msg>", desc: "Commit changes" },
      { cmd: "push, pull", desc: "Sync with remote" },
      { cmd: "checkout <branch>", desc: "Switch branches" },
      { cmd: "git-init, git-clone", desc: "Initialize/clone repos" },
      { cmd: "git-undo, git-clean", desc: "Undo operations" },
      { cmd: "gh <cmd>", desc: "GitHub CLI" },
      { cmd: "gh-run, gh-workflow", desc: "GitHub Actions" },
      { cmd: "gh-pr, gh-issue", desc: "PRs and Issues" },
      { cmd: "glab <cmd>", desc: "GitLab CLI" },
    ],
  },
  {
    id: "ai",
    name: "AI/ML Platforms",
    icon: "🤖",
    color: "#a855f7",
    commands: [
      { cmd: "openai <prompt>", desc: "OpenAI GPT" },
      { cmd: "claude <prompt>", desc: "Anthropic Claude" },
      { cmd: "gemini <prompt>", desc: "Google Gemini" },
      { cmd: "vertex", desc: "Vertex AI" },
      { cmd: "huggingface <model>", desc: "HuggingFace Hub" },
      { cmd: "cohere <prompt>", desc: "Cohere AI" },
      { cmd: "openrouter <prompt>", desc: "OpenRouter.ai" },
      { cmd: "replicate <model>", desc: "Replicate" },
      { cmd: "perplexity <query>", desc: "Perplexity AI" },
      { cmd: "bedrock <prompt>", desc: "AWS Bedrock" },
      { cmd: "together <prompt>", desc: "Together.ai" },
      { cmd: "langchain", desc: "LangChain CLI" },
      { cmd: "crewai", desc: "CrewAI" },
      { cmd: "autogen", desc: "AutoGen" },
      { cmd: "ask, ai", desc: "Universal AI ask" },
    ],
  },
  {
    id: "messaging",
    name: "Messaging & Social",
    icon: "💬",
    color: "#4d9fff",
    commands: [
      { cmd: "telegram <msg>", desc: "Send Telegram message" },
      { cmd: "telegram-file <f>", desc: "Send file via Telegram" },
      { cmd: "discord <msg>", desc: "Discord message" },
      { cmd: "discord-webhook", desc: "Webhook send" },
      { cmd: "slack <msg>", desc: "Slack message" },
      { cmd: "whatsapp <msg>", desc: "WhatsApp message" },
      { cmd: "twitter-post <txt>", desc: "Twitter/X post" },
      { cmd: "facebook-post", desc: "Facebook post" },
      { cmd: "tiktok-post", desc: "TikTok upload" },
      { cmd: "send <service> <msg>", desc: "Universal sender" },
      { cmd: "msg <svc> <msg>", desc: "Quick send" },
      { cmd: "sms", desc: "SMS via email" },
    ],
  },
  {
    id: "cloud",
    name: "Cloud & Serverless",
    icon: "☁️",
    color: "#06b6d4",
    commands: [
      { cmd: "vercel <cmd>", desc: "Vercel deploy" },
      { cmd: "netlify <cmd>", desc: "Netlify deploy" },
      { cmd: "flyctl <cmd>", desc: "Fly.io" },
      { cmd: "railway <cmd>", desc: "Railway" },
      { cmd: "render <cmd>", desc: "Render" },
      { cmd: "heroku <cmd>", desc: "Heroku" },
      { cmd: "supabase <cmd>", desc: "Supabase" },
      { cmd: "aws-lambda", desc: "AWS Lambda" },
      { cmd: "google-functions", desc: "GCP Functions" },
      { cmd: "azure-functions", desc: "Azure Functions" },
      { cmd: "cloudflare-workers", desc: "CF Workers" },
    ],
  },
  {
    id: "google",
    name: "Google Ecosystem",
    icon: "🔵",
    color: "#4d9fff",
    commands: [
      { cmd: "gcloud <cmd>", desc: "Google Cloud CLI" },
      { cmd: "firebase", desc: "Firebase CLI" },
      { cmd: "flutter <cmd>", desc: "Flutter SDK" },
      { cmd: "dart <cmd>", desc: "Dart language" },
      { cmd: "gemini", desc: "Gemini AI" },
      { cmd: "gsutil <cmd>", desc: "GCS utilities" },
      { cmd: "google-play", desc: "Google Play" },
      { cmd: "vertex", desc: "Vertex AI" },
    ],
  },
  {
    id: "docker",
    name: "Containers & K8s",
    icon: "🐳",
    color: "#4d9fff",
    commands: [
      { cmd: "docker <cmd>", desc: "Docker CLI" },
      { cmd: "docker-compose", desc: "Docker Compose (dc)" },
      { cmd: "podman", desc: "Podman" },
      { cmd: "kubectl <cmd>", desc: "Kubernetes" },
      { cmd: "helm <cmd>", desc: "Helm charts" },
      { cmd: "k9s", desc: "K9s dashboard" },
      { cmd: "istio <cmd>", desc: "Istio" },
      { cmd: "argocd <cmd>", desc: "ArgoCD" },
      { cmd: "flux <cmd>", desc: "Flux CD" },
      { cmd: "buildah", desc: "Buildah" },
    ],
  },
  {
    id: "blockchain",
    name: "Blockchain & Web3",
    icon: "⛓️",
    color: "#f97316",
    commands: [
      { cmd: "solana <cmd>", desc: "Solana blockchain" },
      { cmd: "ethers", desc: "Ethers.js" },
      { cmd: "hardhat", desc: "Ethereum dev environment" },
      { cmd: "truffle", desc: "Truffle framework" },
      { cmd: "foundry", desc: "Foundry" },
      { cmd: "web3js", desc: "Web3.js" },
      { cmd: "ipfs", desc: "IPFS" },
      { cmd: "alchemy", desc: "Alchemy API" },
      { cmd: "infura", desc: "Infura" },
    ],
  },
  {
    id: "data",
    name: "Data Engineering",
    icon: "📊",
    color: "#00ff88",
    commands: [
      { cmd: "airflow", desc: "Apache Airflow" },
      { cmd: "dbt", desc: "Data build tool" },
      { cmd: "spark", desc: "Apache Spark" },
      { cmd: "duckdb", desc: "DuckDB" },
      { cmd: "snowflake", desc: "Snowflake" },
      { cmd: "bigquery", desc: "BigQuery" },
      { cmd: "mlflow", desc: "MLflow" },
      { cmd: "wandb", desc: "Weights & Biases" },
      { cmd: "polars", desc: "Polars" },
    ],
  },
  {
    id: "ml",
    name: "Machine Learning",
    icon: "🧠",
    color: "#ec4899",
    commands: [
      { cmd: "pytorch", desc: "PyTorch" },
      { cmd: "tensorflow", desc: "TensorFlow" },
      { cmd: "keras", desc: "Keras" },
      { cmd: "sklearn", desc: "Scikit-learn" },
      { cmd: "transformers", desc: "HuggingFace Transformers" },
      { cmd: "diffusers", desc: "Diffusers" },
      { cmd: "jax", desc: "JAX" },
      { cmd: "onnx", desc: "ONNX" },
      { cmd: "xgboost", desc: "XGBoost" },
      { cmd: "ultralytics", desc: "Ultralytics YOLO" },
    ],
  },
  {
    id: "monitoring",
    name: "Monitoring & Tracing",
    icon: "📈",
    color: "#f97316",
    commands: [
      { cmd: "prometheus", desc: "Prometheus" },
      { cmd: "grafana", desc: "Grafana" },
      { cmd: "datadog <cmd>", desc: "Datadog" },
      { cmd: "newrelic", desc: "New Relic" },
      { cmd: "sentry", desc: "Sentry" },
      { cmd: "kibana", desc: "Kibana" },
      { cmd: "jaeger", desc: "Jaeger tracing" },
      { cmd: "loki", desc: "Grafana Loki" },
    ],
  },
  {
    id: "security",
    name: "Security & Secrets",
    icon: "🔐",
    color: "#ef4444",
    commands: [
      { cmd: "vault", desc: "HashiCorp Vault" },
      { cmd: "keycloak", desc: "Keycloak" },
      { cmd: "auth0", desc: "Auth0" },
      { cmd: "clerk", desc: "Clerk" },
      { cmd: "snyk", desc: "Snyk security scan" },
      { cmd: "trivy", desc: "Trivy" },
      { cmd: "sonarqube", desc: "SonarQube" },
    ],
  },
  {
    id: "testing",
    name: "Testing & QA",
    icon: "🧪",
    color: "#00ff88",
    commands: [
      { cmd: "cypress <cmd>", desc: "Cypress E2E" },
      { cmd: "playwright <cmd>", desc: "Playwright" },
      { cmd: "jest <cmd>", desc: "Jest" },
      { cmd: "vitest", desc: "Vitest" },
      { cmd: "pytest <cmd>", desc: "PyTest" },
      { cmd: "puppeteer <cmd>", desc: "Puppeteer" },
      { cmd: "selenium <cmd>", desc: "Selenium" },
    ],
  },
  {
    id: "mobile",
    name: "Mobile Development",
    icon: "📱",
    color: "#4d9fff",
    commands: [
      { cmd: "expo <cmd>", desc: "Expo (React Native)" },
      { cmd: "react-native", desc: "React Native CLI" },
      { cmd: "flutter <cmd>", desc: "Flutter" },
      { cmd: "adb <cmd>", desc: "Android Debug" },
      { cmd: "fastlane", desc: "Fastlane" },
      { cmd: "ionic", desc: "Ionic" },
      { cmd: "capacitor", desc: "Capacitor" },
    ],
  },
  {
    id: "runtimes",
    name: "Runtimes & Languages",
    icon: "⚡",
    color: "#eab308",
    commands: [
      { cmd: "node", desc: "Node.js" },
      { cmd: "deno", desc: "Deno" },
      { cmd: "bun", desc: "Bun" },
      { cmd: "python", desc: "Python" },
      { cmd: "go", desc: "Go" },
      { cmd: "rust / cargo", desc: "Rust" },
      { cmd: "java", desc: "Java" },
      { cmd: "kotlin", desc: "Kotlin" },
      { cmd: "swift", desc: "Swift" },
      { cmd: "zig", desc: "Zig" },
    ],
  },
  {
    id: "quick",
    name: "Quick Actions",
    icon: "⚡",
    color: "#00ff88",
    commands: [
      { cmd: "ip", desc: "Show IP address" },
      { cmd: "weather", desc: "Show weather" },
      { cmd: "qr <text>", desc: "Generate QR code" },
      { cmd: "passgen [n]", desc: "Generate password" },
      { cmd: "timestamp", desc: "Current timestamp" },
      { cmd: "uuid", desc: "Generate UUID" },
      { cmd: "base64", desc: "Base64 encode/decode" },
      { cmd: "json-format", desc: "Format JSON" },
      { cmd: "url-encode", desc: "URL encode" },
    ],
  },
];

export const stats = {
  commands: 700,
  categories: categories.length,
  aliases: 50,
  platforms: "Any",
};
